/*
 * Ants for Master System
 * An Ants clone for the Sega Master System
 *
 * Bank 2 - Title VDP Pattern data.
 *
 * NOTE: For now, this is manually created with a couple of sizes
 *       populated for sizeof () support. Moving forward, this header
 *       should become auto-generated by Sneptile.
 */

extern const uint32_t cursor_patterns [64];
extern const uint32_t title_patterns [3184];
