/*
 * Ants for Master System
 * An Ants clone for the Sega Master System
 *
 * Bank 3 - Gameplay VDP Pattern data.
 *
 * NOTE: For now, this is manually created with a couple of sizes
 *       populated for sizeof () support. Moving forward, this header
 *       should become auto-generated by Sneptile.
 */

extern const uint32_t player_patterns [256];
extern const uint32_t panel_patterns [392];
extern const uint32_t castles_patterns [];
extern const uint32_t fence_patterns [];
extern const uint32_t background_patterns [208];
